# This is the config file for travis-ci for PINT

language: python
sudo: required
python: 2.7

env:
    - TOXENV=py36
    - TOXENV=py35
    - TOXENV=py27

install: pip install -U tox

script: tox -e ${TOXENV}

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

after_success:
    - coveralls
