# This is the config file for travis-ci for PINT

language: python
sudo: required
python: 
    - 2.7
    - 3.5
    - 3.6

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

install: pip install -U tox-travis

script: tox 

after_success:
    - coveralls
